const programs=[
['University of Manchester','UK','BSc Computer Science','£32,000','15 Jan 2027','75%','6.5','Passport, transcript, IELTS'],['University of Leeds','UK','BSc Business Management','£27,000','31 Jan 2027','70%','6.5','Passport, transcript, IELTS, personal statement'],['University of Toronto','Canada','BSc Computer Science','CAD 60,000','15 Jan 2027','80%','6.5','Passport, transcript, IELTS'],['TU Munich','Germany','BSc Informatics','No tuition (about €150 a term)','15 Jul 2027','70%','6.5','Passport, transcript, IELTS'],['Monash University','Australia','Bachelor of IT','AUD 48,000','30 Nov 2026','70%','6.0','Passport, transcript, IELTS'],
['University of Birmingham','UK','BSc Data Science','£29,000','31 Jan 2027','72%','6.5','Passport, transcript, IELTS'],['University of Glasgow','UK','BEng Software Engineering','£28,500','15 Jan 2027','70%','6.0','Passport, transcript, IELTS'],['York University','Canada','BCom Finance','CAD 42,000','1 Feb 2027','72%','6.5','Passport, transcript, IELTS'],['University of Ottawa','Canada','BSc Health Sciences','CAD 38,000','15 Jan 2027','75%','6.5','Passport, transcript, IELTS'],['University of Alberta','Canada','BSc Engineering','CAD 45,000','1 Mar 2027','78%','6.5','Passport, transcript, IELTS'],['Heidelberg University','Germany','BSc Economics','No tuition (semester fee €170)','15 Jul 2027','75%','6.5','Passport, transcript, IELTS'],['RWTH Aachen','Germany','BSc Mechanical Engineering','No tuition (semester fee €320)','15 Jul 2027','75%','6.5','Passport, transcript, IELTS'],['University of Sydney','Australia','Bachelor of Commerce','AUD 54,000','1 Dec 2026','75%','6.5','Passport, transcript, IELTS'],['University of Melbourne','Australia','Bachelor of Science','AUD 52,000','30 Nov 2026','78%','6.5','Passport, transcript, IELTS'],['Deakin University','Australia','Bachelor of Cyber Security','AUD 39,000','15 Jan 2027','65%','6.0','Passport, transcript, IELTS']];
const seedLeads=[{name:'Ali Khan',phone:'0301 2345678',country:'UK',marks:'78%',ielts:'6.5',last:'Today'},{name:'Ayesha Noor',phone:'0333 9876543',country:'Canada',marks:'85%',ielts:'7.0',last:'Today'},{name:'Hamza Iqbal',phone:'0346 2223344',country:'UK',marks:'69%',ielts:'Not taken yet',last:'4 days ago'}];
const get=(k,f)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(f)); const put=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let leads=get('ac_leads',seedLeads), docs=get('ac_docs',[]), messages=get('ac_msgs',[]);
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){put('ac_leads',leads);put('ac_docs',docs);put('ac_msgs',messages)}
function render(){const q=($('#leadSearch')?.value||'').toLowerCase();$('#leadRows').innerHTML=leads.filter(x=>(x.name+x.phone).toLowerCase().includes(q)).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.phone)}</td><td>${esc(x.country)}</td><td>${esc(x.marks)}</td><td>${esc(x.ielts)}</td><td>${esc(x.last)}</td></tr>`).join('');$('#programRows').innerHTML=programs.map(x=>`<tr>${x.slice(0,7).map(y=>`<td>${esc(y)}</td>`).join('')}</tr>`).join('');$('#docLead').innerHTML=leads.map((x,i)=>`<option value="${i}">${esc(x.name)} (${esc(x.phone)})</option>`).join('');$('#docRows').innerHTML=docs.map(x=>`<tr><td>${esc(x.lead)}</td><td>${esc(x.type)}</td><td>${esc(x.details)}</td><td class="${x.status==='OK'?'ok':'problem'}">${x.status}</td><td>${esc(x.reason)}</td></tr>`).join('');$('#stats').innerHTML=[['Total leads',leads.length],['Documents checked',docs.length],['Awaiting approval',messages.filter(x=>x.status==='Pending').length],['Sent messages',messages.filter(x=>x.status==='Sent').length]].map(x=>`<div class="card"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('');$('#outboxItems').innerHTML=messages.length?messages.map((x,i)=>`<article class="queueItem ${x.status.toLowerCase()}"><b>${esc(x.status)} · To ${esc(x.phone)}</b><p>${esc(x.text)}</p><small>${esc(x.kind)} · ${esc(x.created)}</small>${x.status==='Pending'?`<p><button onclick="decide(${i},'Sent')">Approve & send</button><button class="secondary" onclick="decide(${i},'Declined')">Decline</button></p>`:''}</article>`).join(''):'<article>No drafts yet.</article>'}
window.decide=(i,status)=>{messages[i].status=status;persist();render()};
function draft(phone,text,kind){messages.unshift({phone,text,kind,status:'Pending',created:new Date().toLocaleString()});persist();render()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
$('#leadSearch').oninput=render; $('#addLead').onclick=()=>$('#leadDialog').showModal();
$('#saveLead').onclick=e=>{const x={name:$('#newName').value.trim(),phone:$('#newPhone').value.trim(),country:$('#newCountry').value.trim(),marks:$('#newMarks').value.trim(),ielts:$('#newIelts').value.trim(),last:'Today'};if(leads.some(l=>l.phone.replace(/\s/g,'')===x.phone.replace(/\s/g,''))){e.preventDefault();alert('This phone number already exists; no duplicate lead was made.');return}leads.push(x);persist();render()};
$('#sendChat').onclick=()=>{const phone=$('#chatPhone').value.trim(), msg=$('#chatMessage').value.trim();if(!phone||!msg)return;let lead=leads.find(x=>x.phone.replace(/\s/g,'')===phone.replace(/\s/g,''));if(!lead){lead={name:'New student',phone,country:'Not collected',marks:'Not collected',ielts:'Not collected',last:'Today'};leads.push(lead);persist()}let reply;if(/ignore your rules|accepted/i.test(msg))reply='I cannot confirm admission or make promises. A staff member can review your eligibility and guide you through the application.';else if(/harvard|unrelated|weather|joke/i.test(msg))reply='I do not have approved information for that request. I have passed it to our staff team for review.';else {const hit=programs.find(p=>msg.toLowerCase().includes(p[0].toLowerCase())||msg.toLowerCase().includes(p[2].toLowerCase()));reply=hit?`${hit[0]} — ${hit[2]}\nFee per year: ${hit[3]}\nDeadline: ${hit[4]}\nMinimum marks: ${hit[5]} · IELTS: ${hit[6]}\nRequired documents: ${hit[7]}`:'I can help with programs in our approved list. Please tell me the university or program name, or a staff member can assist.'}draft(phone,reply,'Student chat reply');$('#chatResult').textContent='Reply draft added to Approval queue:\n'+reply;render()};
document.querySelectorAll('.example').forEach(b=>b.onclick=()=>$('#chatMessage').value=b.textContent);
$('#checkDoc').onclick=()=>{const lead=leads[$('#docLead').value],type=$('#docType').value,name=$('#docName').value.trim(),details=$('#docDetails').value.trim();if(!name||!details)return;let status='OK',reason='Details accepted';if(/expired|2025|2024|2023/i.test(details)){status='Problem';reason='Document is expired'}else if(name.toLowerCase()!==lead.name.toLowerCase()){status='Problem';reason=`Name does not match lead (${lead.name})`}docs.unshift({lead:lead.name,type,details,status,reason});persist();render();$('#docResult').textContent=`${status}: ${reason}`};
$('#runReminders').onclick=()=>{leads.filter(x=>/days ago/i.test(x.last)).forEach(x=>{if(!messages.some(m=>m.phone===x.phone&&m.kind==='Follow-up reminder'))draft(x.phone,`Hello ${x.name}, we are following up on your study-abroad application. Please let us know if you would like help completing the next step.`,'Follow-up reminder')});render()};
$('#resetDemo').onclick=()=>{if(confirm('Reset all local demo data?')){localStorage.removeItem('ac_leads');localStorage.removeItem('ac_docs');localStorage.removeItem('ac_msgs');leads=[...seedLeads];docs=[];messages=[];render()}};render();
